apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  # URL은 Docker Compose 네트워크 내부에서 Prometheus 컨테이너 이름과 포트를 사용합니다.
  url: http://prometheus:9090
  isDefault: true
  editable: true
  uid: prometheusdatasource