clusters = A, B

A.bootstrap.servers = broker-a-1:29092,broker-a-2:29092,broker-a-3:29092
B.bootstrap.servers = broker-b:39092

A->B.enabled = true
B->A.enabled = false
A->B.topics = barcode-events,barcode-events-dlt
A->B.groups = barcode-processing-group

replication.policy.class = org.apache.kafka.connect.mirror.IdentityReplicationPolicy
A->B.replication.policy.class = org.apache.kafka.connect.mirror.IdentityReplicationPolicy
A->B.replication.factor = 1

A->B.emit.heartbeats.enabled = true
A->B.emit.checkpoints.enabled = true
A->B.sync.group.offsets.enabled = true
A->B.sync.group.offsets.interval.seconds = 5
A->B.emit.checkpoints.interval.seconds = 5
A->B.refresh.topics.interval.seconds = 5
A->B.refresh.groups.interval.seconds = 5
A->B.offset-syncs.topic.location = target
A->B.sync.topic.configs.enabled = false
A->B.sync.topic.acls.enabled = false

heartbeats.topic.replication.factor = 1
checkpoints.topic.replication.factor = 1
offset-syncs.topic.replication.factor = 1

config.storage.replication.factor = 1
offset.storage.replication.factor = 1
status.storage.replication.factor = 1

listeners = HTTP://0.0.0.0:8083
rest.advertised.host.name = mm2
rest.port = 8083
tasks.max = 3
consumer.auto.offset.reset = earliest
producer.acks = all
producer.enable.idempotence = true
